# generate a cix script to download all the help files
# usage: cat help.lst | awk -f one.awk | sort | awk -f scr.awk > scriptfile
BEGIN { print "REM script to get all helpfiles"
        print "REM Devans 14dec2005"
	print "REM generated by an awk script see c:\\cixman95"
	print "status \"getting help files\"";
	print "put \"killscratch\"";
	print "waitfor \"M:\"";
	}
{ printf "put \"file echo ============== %s =============\"\n", $1;
  printf "waitfor \"M:\"\n";
  printf "put \"file help %s\"\n",$1;
  printf "waitfor \"M:\"\n"
  
  }
END {print "put \"download\"";
     print "download \"c:\\cixman95\\helpfile.txt\"";


}
	

